### ISSUE TITLE
authentication error

### ISSUE THREAD

**Issue by brendonwo** [ChuckMac/tadpoles-scraper#1]
Hi 
thanks for this scraper, could save me a few hours of clicking 2 years of links

Starting Tadpoles Scraper...
  -- Authenticating brendonw@gmail.com
Authentication Error

x2 checked my user and password  it is correct.
anything else

**Comment by ChuckMac** [comment]
@brendonwo I would suggest changing line 59 in `index.js` from:

```
		console.log('Authentication Error')
```

To:

```
		console.log('Authentication Error ' + error)
```

Not going to fix it, but should at least give you more information on what the error is.

**Comment by brendonwo** [comment]
ok,
Authentication ErrorError: Request failed with status code 403
just forbidden?
brendon

**Comment by ChuckMac** [comment]
403 is generally going to be invalid credentials.  Are you 100% sure its correct in the config?  No extra spaces around it or anything?

**Comment by brendonwo** [comment]
even changed it to not contain special char ,,also went to googl and
allowed less secure logins
no joy ;-(

**Comment by ChuckMac** [comment]
Oh, are you using Google sign in?

**Comment by brendonwo** [comment]
Yes. I am using a google sign in.

**Comment by ChuckMac** [comment]
Sorry, only email login is supported by this.

**Comment by brendonwo** [comment]
Ok i will have change that.
Thanks. Did not expect a response so fast.

**Comment by brendonwo** [comment]
changed to email login
that works !
