### ISSUE TITLE
Add support for downloading PDF

### ISSUE THREAD

**Issue by stevemerckel** [ChuckMac/tadpoles-scraper#10]
I'd like to propose changing the supported file types to include PDF files.

Locally I added this in the large `if-else if` block around line 196:
```javascript
} else if (response.headers['content-type'] == 'application/pdf') {
    filename = dirbase + filebase + '.pdf'
    fs.writeFileSync(filename, response.data)
}
```

The caveat with the change is that it is _always_ re-downloaded -- so some extra work would be needed in the "maybe"-named functions.  I'm happy to submit a PR for this as well.

**Comment by ChuckMac** [comment]
Hey @stevemerckel.  Thanks for the suggestions.  At this point my children haven't gone to a facility with Tadpoles in several years so I don't have the ability to test/develop this anymore.  I'm happy to pull it in if you want to create a PR.

**Comment by stevemerckel** [comment]
I created the pull request for this change -- #11
