### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by digitek007** [ChuckMac/tadpoles-scraper#3]
Awesome that I found this - saved me many hours of saving images as my child is moving schools and leaving tadpoles.  Will do a bit of digging to see if I can add - would be very useful if you could also save the associated text with the tadpoles image entry with an identically named .txt file.

**Comment by stevemerckel** [comment]
I actually implemented this idea on my local copy.  I'll create a PR for that soon for review.

**Comment by stevemerckel** [comment]
I created a PR for this -- #13

**Comment by stevemerckel** [comment]
> I created a PR for this -- #13

This PR was approved and merged.
